### ISSUE TITLE
Only black and white on Inky What Yellow

### ISSUE THREAD

**Issue by Wahala** [seaniedan/weatherWHAT#3]
Hi there and happy new Year,
Not sure if this is a problem with your code or my hardware or some instructions I've missed.
I've installed as per your instructions on a Pi zero W with the Pi OS Lite and it is plugged into a Inky What Yellow.
I can run weatherWHAT.py with the -i switch and it runs and update the Inky What screen, but I only get a black grayscale image displayed, just black and white with greys.

If I run the Inky examples from piromoni then it can display in yellow ok.

The only think I haven't done as per your instructions (I believe) is I'm not running it in a venv as I'm not planning to run anything else on the Pi.

Any idea where to look for a solution to this? 
I've looked at WeatherDisplay.py and it seems to be pre set to use yellow already.
![image](https://github.com/seaniedan/weatherWHAT/assets/17151410/2e00b5dd-cf8a-4e6d-b927-0087545ca71e)

**Comment by coinish** [comment]
Oh no! Most likely a problem with my code. You don't need a venv.

What happens if you add 

--inky_colour yellow

**Comment by Wahala** [comment]
`--colour yellow` fixes it indeed cheers, only the temperature is in yellow at the moment but in daytime the sun would be yellow too I guess.
